# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 11:52
from __future__ import unicode_literals

import django.db.models.deletion
import django_extensions.db.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audiokitt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyse',
            options={'ordering': ('-created',), 'verbose_name': 'Analyse', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ('-created',), 'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AddField(
            model_name='analyse',
            name='data',
            field=django_extensions.db.fields.json.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='file_md5',
            field=models.CharField(db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Done'), (2, 'Processing'), (99, 'Error')],
                                              default=0),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='analyse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries',
                                    to='audiokitt.Analyse'),
        ),
    ]
