# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiokitt', '0002_auto_20160512_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyse',
            old_name='data',
            new_name='analyse_data',
        ),
    ]
